{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "gcloud-sqlproxy.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "gcloud-sqlproxy.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "gcloud-sqlproxy.fullname" . }}
{{ .Values.podDisruptionBudget | indent 2 }}
{{- end -}}
